[package]
name = "tablo-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Procedural macros for Tablo."

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3", features = ["full"] }
